### ISSUE TITLE
Option to only add new tracks

### ISSUE THREAD

**Issue by Sheugel** [WritheM/IntelliMerge#32]
I would like the option to add only new tracks to a master playlist.

By new tracks, I mean tracks added to the source playlist(s) after the last scan by Intellimerge.
At the moment, Intellimerge will also add older tracks if they are not present in the master playlist.

My goal is to build a music discovery system with:
- a first master playlist where source playlists are added into a big playlist with no duplicates
- a second master playlist where only the new tracks added to the first master playlist are added
In the second master playlist, I will pick (=add to another playlist of picked tracks) then delete the songs I like, and delete the songs I don't like.  The pick and delete system will be random because I will not necesseraly pick the songs in the order they appear in the playlist. I want to delete the songs to be sure I don't listen twice to a song (I don't like).

Thanks

**Comment by pironic** [comment]
I might have a work-around with our current functionality... albeit with an extra step to your desired workflow... If you create a third playlist and link it to your master as a blacklisted playlist, then every time you want to remove a song from your master playlist, you first add it to this new blacklist playlist before deleting the track, it will not re-add that song to the master; even if it shows up on any of the linked playlists. 

The complexity increase that would be required to implement what you're looking for is extraordinarily high to just save that extra click. I'm not going to lie. I'm not going to be able to put this on the development docket for a while. Maybe as a nice to have far down the road or if there is a large outcry for similar functionality. We can revisit later but given that there is a work-around already available I'm going to defer this as far down the road as possible. Thank you for the suggestion anyway!

The biggest hindrance to this is knowing what the state of the playlist WAS in order to determine what is new. The only way I can think to do that is to log a playlist's contents over time... if you check the stats on our runs on the FAQ page we've been responsible for >300m track adds alone. That's a lot of extra data to capture. ~2k users. ~20k playlist links. potentially 10k songs in each... then tracking that over time. That's a lot of data!
