### ISSUE TITLE
Not adding anyt music to master playlist

### ISSUE THREAD

**Issue by kevink86** [WritheM/IntelliMerge#37]
I love your tool. But when I try to link playlists, but nothing appears in my master playlist. After adding i get the follow: 

**Describe the bug**
[{"id":4254,"enabled":true,"spotify_id":"6DSmA6drLO5FPzQtgvXiBF","username":"kevinkromhout","title":"Totaal nov 2024","options":{"coverart":1,"remove_old":1},"history":[{"id":0,"date":1731079175,"who":"System","entry":"Last update"},{"id":"2rry","date":1731079353,"who":"kevinkromhout","entry":"Enabled the Master Playlist"},{"id":"2rrx","date":1731079349,"who":"kevinkromhout","entry":"Disabled the Master Playlist"},{"id":"2rrr","date":1731079183,"who":"kevinkromhout","entry":"Linked to a Spotify Playlist."},{"id":"2rrq","date":1731079176,"who":"kevinkromhout","entry":"Created New Master Playlist"}],"webhooks":[],"links":[{"mpl_id":4254,"0":4254,"spotify_id":"0vFRUxNkB46fyRxCegKxlG","1":"0vFRUxNkB46fyRxCegKxlG","mode":1,"2":1},{"mpl_id":4254,"0":4254,"spotify_id":"2kfQmvPC7bsED76klZQBq3","1":"2kfQmvPC7bsED76klZQBq3","mode":1,"2":1},{"mpl_id":4254,"0":4254,"spotify_id":"31nzllulPNPAceFAH24yx4","1":"31nzllulPNPAceFAH24yx4","mode":1,"2":1},{"mpl_id":4254,"0":4254,"spotify_id":"3fkPqJizBunn6qfLTxShCJ","1":"3fkPqJizBunn6qfLTxShCJ","mode":1,"2":1},{"mpl_id":4254,"0":4254,"spotify_id":"3j6lbFRqmw58QL1Z8rpl3j","1":"3j6lbFRqmw58QL1Z8rpl3j","mode":1,"2":1}]}]

Technical Details: TypeError: Cannot read properties of null (reading '0')

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Build [e.g. 3500] (This is found on the about/faq page in the change log section.

**Smartphone (please complete the following information):**
 - Build [e.g. 3500] (This is found on the about/faq page in the change log section.

**Additional context**

**Comment by pironic** [comment]
Thanks for using our tool @kevink86  :) 

There are two things going on here: 

I just took a look and it looks as though you created a new playlist, then clicked the +Create button , then started making your links. As you're on a free plan, it only updates once a day for you... so as soon as it was created on Spotify, it scanned it and found no new songs to add. You would need to wait until tomorrow for it to find more songs and add them. In future if you wait to click +Create until after you've made your links the first scan wont happen until you're ready. I manually reset the timers on your list, so that the scanner would manually pick it up again and it did without issue. It generated your first days list for you :) 

The second is the error about reading properties of null. This is a known glitch that I've been trying to nail down and hope to fix in the next major version... it's just a UI glitch though, so refreshing the page will usually solve it. I think it happens when it's trying to load a list of followed playlists and it collides for some reason with the list of linked playlists. It tries to build the appropriate buttons when comparing the two lists and fails for some reason to  load one or the other into memory. I need further time to diagnose it... and it's not every time it happens, so it's proving very difficult to locate... anyway, rambling aside: i'm aware of it and will fix it as soon as i can :) Likely in the new year.

Thanks again for the report, and supporting the product!

**Comment by kevink86** [comment]
Thanks for your reply, i understand! Again thanks for this great tool! And thanks for the help, i'm gonna add more playlists now.
